### ISSUE TITLE
Consider splitting out user configuration into separate files

### ISSUE THREAD

**Issue by rickerbh** [simple-machines/ansible-template#45]
When configuring this for the first time I found myself wanting to split out the infra config into separate files, but the default structure for the section was to have a single `main.yml` file. I know it's not much effort to add in another file for each of the infra types (to replicate the defaults) but having empty config files by default for each of the infra types would probably help guide people into a more modular structure of their configuration. Just a thought.

**Comment by simplesteph** [comment]
agreed, although that's something the user could potentially do on their own as they own that folder? I'll see how easy it is to incorporate while maintaining backwards compatibiltiy

**Comment by rickerbh** [comment]
Absolutely the user can do this on their own. I think it's more about guiding them as to what's the best structure. If putting everything in a single file is best, leave as is. If there is something to be gained (in terms of understandability of the config, or reuse of more modular files across projects, or some other reason) then it might be a good thing to consider.

**Comment by simplesteph** [comment]
closed by https://github.com/simple-machines/ansible-template/commit/8b814100452e6fcbc337205c294535dedad08c5d
